version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: school-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schooldb
    ports:
      - "8080:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
